##
# Huge thanks to http://www.jacobtomlinson.co.uk/jekyll/2015/02/18/test-you-jekyll-blog-with-travis-ci/
##
language: ruby
# Run in container-based infrastructure
# See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html --href-ignore=# --disable-external
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
