##
# Huge thanks to http://www.jacobtomlinson.co.uk/jekyll/2015/02/18/test-you-jekyll-blog-with-travis-ci/
##
language: ruby

# Run in container-based infrastructure
sudo: false
rvm:
  - 2.1

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --allow-hash-href --disable-external

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
